/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengl_GLRender */

#ifndef _Included_com_example_opengl_GLRender
#define _Included_com_example_opengl_GLRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengl_GLRender
 * Method:    ndkInitGl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_GLRender_ndkInitGl
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opengl_GLRender
 * Method:    ndkPaintGl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_GLRender_ndkPaintGl
  (JNIEnv *, jobject);

/*
 * Class:     com_example_opengl_GLRender
 * Method:    ndkResizeGl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_GLRender_ndkResizeGl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
